# Generated by Django 5.2.8 on 2025-11-22 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.carrera'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
