# Generated by Django 5.2.8 on 2025-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_carrera_alter_usuario_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.habilidad'),
        ),
    ]
