# Generated by Django 5.2.8 on 2025-11-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_habilidad_usuario_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='carrera',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
    ]
