# Generated by Django 5.2.8 on 2025-11-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_tipohabilidad_habilidad_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidad',
            old_name='nombre',
            new_name='nombre_habilidad',
        ),
    ]
