# Generated by Django 5.2.8 on 2025-11-27 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_nombre_habilidad_nombre_habilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='valoraciones',
            field=models.ManyToManyField(blank=True, related_name='valorado_por', through='usuarios.ValoracionUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='valoracionusuario',
            constraint=models.CheckConstraint(condition=models.Q(('evaluador', models.F('evaluado')), _negated=True), name='no_autovaloracion'),
        ),
        migrations.AddConstraint(
            model_name='valoracionusuario',
            constraint=models.UniqueConstraint(fields=('evaluador', 'evaluado'), name='una_valoracion_por_usuario'),
        ),
    ]
