# Generated by Django 5.2.8 on 2025-11-28 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_valoracionusuario_usuario_valoraciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato recomendado: +56912345678', max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', message='Ingresa un número de teléfono válido.')]),
        ),
    ]
