# Generated by Django 5.2.8 on 2025-12-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_matches_solicitudmatch_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
